var MusicSheets = [
  { name: 'Mary Had A Little Lamb',
    notes: [
      {note: '45'},
      {note: '43'},
      {note: '41'},
      {note: '43'},
      {note: '45'},
      {note: '45'},
      {note: '45'},
      {note: '43'},
      {note: '43'},
      {note: '43'},
      {note: '45'},
      {note: '48'},
      {note: '48'},
      {note: '45'},
      {note: '43'},
      {note: '41'},
      {note: '43'},
      {note: '45'},
      {note: '45'},
      {note: '45'},
      {note: '45'},
      {note: '43'},
      {note: '43'},
      {note: '45'},
      {note: '43'},
      {note: '41'}
    ]
  },
  { name: 'Twinkle Twinkle Little Star',
    notes: [
      {note: '41'},
      {note: '41'},
      {note: '48'},
      {note: '48'},
      {note: '410'},
      {note: '410'},
      {note: '48'},

      {note: '46'},
      {note: '46'},
      {note: '45'},
      {note: '45'},
      {note: '43'},
      {note: '43'},
      {note: '41'},

      {note: '48'},
      {note: '48'},
      {note: '46'},
      {note: '46'},
      {note: '45'},
      {note: '45'},
      {note: '43'},

      {note: '48'},
      {note: '48'},
      {note: '46'},
      {note: '46'},
      {note: '45'},
      {note: '45'},
      {note: '43'},

      {note: '41'},
      {note: '41'},
      {note: '48'},
      {note: '48'},
      {note: '410'},
      {note: '410'},
      {note: '48'},

      {note: '46'},
      {note: '46'},
      {note: '45'},
      {note: '45'},
      {note: '43'},
      {note: '43'},
      {note: '41'},

    ]
  }
]

module.exports = MusicSheets;
